/**
 * List of the actions used in the redux flow
 */
const ActionTypes = {

    INIT_APP : 'INIT_APP',
    INIT_APP_SUCCESS : 'INIT_APP_SUCCESS',
    INIT_APP_FAILURE : 'INIT_APP_FAILURE',

    CURRENCIES_VALUES_GET : 'CURRENCIES_VALUES_GET',
    CURRENCIES_VALUES_GET_SUCCESS : 'CURRENCIES_VALUES_GET_SUCCESS',
    CURRENCIES_VALUES_GET_FAILURE : 'CURRENCIES_VALUES_GET_FAILURE',

    CURRENCIES_TOGGLE_INTERVAL: 'CURRENCIES_TOGGLE_INTERVAL',

    WALLET_EXCHANGE_CURRENCY: 'WALLET_EXCHANGE_CURRENCY'
};

export default ActionTypes;
